global using ELDOKKAN.Models;
global using ELDOKKAN.Repositories;
global using ELDOKKAN.Application.DTOs.Admin;
global using ELDOKKAN.Application.DTOs.Category;
global using ELDOKKAN.Application.DTOs.Customer;
global using ELDOKKAN.Application.DTOs.Product;
global using ELDOKKAN.Application.DTOs.Order;
global using ELDOKKAN.Application.DTOs.OrderDetails;
global using AutoMapper;